version: 1.6.0
services:
  data_manager-nginx:
    image: xiexf128/data_manager-nginx:latest
    restart: always
    volumes:
    - uwsgi_data:/tmp/uwsgi/
    - web_static:/var/www/datamanager/assets/:ro
    ports:
    - 8014:80
    depends_on:
    - data_manager-django
  data_manager-django:
    image: xiexf128/data_manager-django:latest
    restart: always
    command: 'sh -c "/venv/bin/python3 manage.py collectstatic --noinput   && /venv/bin/uwsgi   --ini
      /app/datamanager.uwsgi.ini --enable-threads"

      '
    env_file: &id001
    - ./.django_secrets.env
    environment: &id002
      is_docker: 'True'
      system_version: 1.6.0_db36a41
    volumes:
    - uwsgi_data:/tmp/uwsgi/
    - web_static:/app/static/
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/temp/:/app/media/temp/
    - &id003
      type: bind
      source: ./volumes/primary_storage
      target: /app/media/primary_storage
    - &id004
      type: bind
      source: ./volumes/secondary_storage
      target: /app/media/secondary_storage
    - &id005
      type: bind
      source: ./volumes/remote_storage
      target: /app/media/remote_storage
    - &id006
      type: bind
      source: ./volumes/offline_storage
      target: /app/media/offline_storage
  data_manager-JupiterNotebook:
    image: xiexf128/data_manager-django:latest
    restart: always
    command: 'sh -c "/venv/bin/python3 manage.py shell_plus --notebook"

      '
    env_file: *id001
    environment: *id002
    volumes:
    - uwsgi_data:/tmp/uwsgi/
    - web_static:/app/static/
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/temp/:/app/media/temp/
    - *id003
    - *id004
    - *id005
    - *id006
    ports:
    - 8085:8080
volumes:
  uwsgi_data: null
  web_static: null
